package android.app.sportapp.remote

object APIConst {
    //        const val BASE_URL = "https://api-3817264.hombolttech.dev/api/"
    const val BASE_URL = "https://api.yoplaybook.com/api/"
//    const val BASE_URL = "http:///192.168.1.216:5001/api/"

    //    const val SOCKET_URL = "https://api-3817264.hombolttech.dev"
    const val SOCKET_URL = "https://api.yoplaybook.com"
//    const val SOCKET_URL = "http://192.168.1.216:5001"

    // Network Request Params
    const val success = "success"
    const val success_code = "200"
    const val error = "error"
    const val vEmail = "vEmail"
    const val vPassword = "vPassword"
    const val iCountryId = "iCountryId"
    const val vTeamBanner = "vTeamBanner"
    const val eAgeGroup = "eAgeGroup"
    const val vTeamName = "vTeamName"
    const val eNationOrganization = "eNationOrganization"
    const val vNationOrganization = "vNationOrganization"
    const val eLeagueConference = "eLeagueConference"
    const val vLeagueConference = "vLeagueConference"
    const val eSchoolName = "eSchoolName"
    const val vSchoolName = "vSchoolName"
    const val tTeamTagline = "tTeamTagline"
    const val iStateId = "iStateId"
    const val vZipCode = "vZipCode"
    const val eTeamGender = "eTeamGender"
    const val iTeamTypeId = "iTeamTypeId"
    const val vFullName = "vFullName"
    const val dBirthDate = "dBirthDate"
    const val iTeamId = "iTeamId"
    const val iSportId = "iSportId"
    const val iUserId = "iUserId"
    const val iRoleId = "iRoleId"
    const val vImage = "vImage"
    const val eUserType = "eUserType"
    const val eUnder13 = "eUnder13"
    const val Manager = "Manager"
    const val iTeamplayerId = "iTeamplayerId"
    const val vFirstName = "vFirstName"
    const val vLastName = "vLastName"
    const val verifyToken = "verifyToken"
    const val eDeviceType = "eDeviceType"
    const val eDeviceTypeAndroid = "Android"
    const val vTitle = "vTitle"
    const val eType = "eType"
    const val tDescription = "tDescription"
    const val eApproval = "eApproval"
    const val vParentEmail = "vParentEmail"
    const val vUserBanner = "vUserBanner"
    const val iTeammanagerId = "iTeammanagerId"
    const val vOffense = "vOffense"
    const val vDefense = "vDefense"
    const val vFreeDraw = "vFreeDraw"
    const val vBall = "vBall"
    const val iCanvasAndroidId = "iCanvasAndroidId"
    const val vPlayBook = "vPlayBook"
    const val category = "category"
    const val eDeviceTypeYes = "Yes"
    const val subcategoryArray = "subcategoryArray"
    const val iParentId = "iParentId"
    const val vEvent_name = "vEvent_name"
    const val vEvent_date = "vEvent_date"
    const val vFrom_time = "vFrom_time"
    const val vTo_time = "vTo_time"
    const val vLocation = "vLocation"
    const val vNote = "vNote"
    const val vColor = "vColor"
    const val share_To = "share_To"
    const val coach = "coach"
    const val eDevice = "eDevice"
    const val iFacilityId = "iFacilityId"
    const val vDuration = "vDuration"
    const val eTeamType = "eTeamType"
    const val Home = "Home"
    const val Away = "Away"
    const val iEventId = "iEventId"
    const val iChatUserManagementId = "iChatUserManagementId"
    const val iAddedById = "iAddedById"
    const val vMessage = "vMessage"
    const val room = "room"
    const val vUserName = "vUserName"
    const val time = "time"
    const val vFile = "vFile"
    const val iPersonalEventId = "iPersonalEventId"
    const val iSport_groundImageId = "iSport_groundImageId"
    const val vRole = "vRole"
    const val vStart_Date = "vStart_Date"
    const val vEnd_Date = "vEnd_Date"
    const val eRepeat = "eRepeat"
    const val tRepeatEvent = "tRepeatEvent"
    const val vPositions = "vPositions"
    const val iJerseyNumber = "iJerseyNumber"
    const val iSportPositionId = "iSportPositionId"
    const val vWeeklyDay = "vWeeklyDay"
    const val vMonthlyDay = "vMonthlyDay"
    const val vYearlyDay = "vYearlyDay"
    const val Team_Name = "Team_Name"
    const val Sport_Name = "Sport_Name"
    const val updates = "Updates"
    const val iWebsiteid = "iWebsiteid"
    const val iSocialLinkId = "iSocialLinkId"
    const val iLanguagetransId = "iLanguagetransId"
    const val vSecondaryNumber = "vSecondaryNumber"
    const val vSecondaryEmail = "vSecondaryEmail"
    const val eGender = "eGender"
    const val eRelationship = "eRelationship"
    const val iEducationId = "iEducationId"
    const val iSecondaryschoolId = "iSecondaryschoolId"
    const val iWorkplaceId = "iWorkplaceId"
    const val vHomeTown = "vHomeTown"
    const val vCurrentCity = "vCurrentCity"
    const val iLanguageId = "iLanguageId"
    const val vUrl = "vUrl"
    const val vSocialMediaName = "vSocialMediaName"
    const val iSocialMediaId = "iSocialMediaId"
    const val vUniversity = "vUniversity"
    const val vPartner = "vPartner"
    const val vStartDay = "vStartDay"
    const val vStartMonth = "vStartMonth"
    const val vStartYear = "vStartYear"
    const val vEndDay = "vEndDay"
    const val vEndMonth = "vEndMonth"
    const val vEndYear = "vEndYear"
    const val eGraduate = "eGraduate"
    const val vCourse1 = "vCourse1"
    const val vCourse2 = "vCourse2"
    const val vCourse3 = "vCourse3"
    const val eAttendfor = "eAttendfor"
    const val vDegree = "vDegree"
    const val vCompany = "vCompany"
    const val vPosition = "vPosition"
    const val vCity = "vCity"
    const val eCurrentlyWorking = "eCurrentlyWorking"
    const val vCountryCode = "vCountryCode"
    const val vValue = "vValue"
    const val vDivision = "vDivision"
    const val vType = "vType"
    const val vLeague = "vLeague"
    const val iTeamLeagueTransId = "iTeamLeagueTransId"
    const val vTeamLogo = "vTeamLogo"
    const val vBusinessName = "vBusinessName"
    const val eRevivalTeamType = "eRevivalTeamType"
    const val vRevivalTeamName = "vRevivalTeamName"
    const val eSchedule = "eSchedule"
    const val vChannelName = "vChannelName"
    const val vAddress = "vAddress"
    const val vGameName = "vGameName"
    const val eDeviceTypeNormal = "Normal"
    const val vMobileNumber = "vMobileNumber"
    const val tandc = "tandc"
    const val channel = "channel"
    const val vOTP = "vOTP"
    const val vRegistrationAuthCode = "vRegistrationAuthCode"
    const val iUserhobbiesId = "iUserhobbiesId"
    const val userHobbies = "userHobbies"
    const val iHobbiesId = "iHobbiesId"
    const val iPostId = "iPostId"
    const val vCoachPrice = "vCoachPrice"
    const val vDirectPayment = "vDirectPayment"
    const val vSlot = "vSlot"
    const val eWaitList = "eWaitList"
    const val eDirectPayment = "eDirectPayment"
    const val sms = "sms"
    const val eInfinite = "eInfinite"
    const val eFacility = "eFacility"
    const val iRevivalTeamid = "iRevivalTeamid"
    const val eSportType = "eSportType"
    const val permissions = "permissions"
    const val iSportsVideoId = "iSportsVideoId"
    const val vPersonalSlug = "vPersonalSlug"
    const val name = "name"
    const val vCurrency = "vCurrency"
    const val iProductId = "iProductId"
    const val vUnitAmount = "vUnitAmount"
    const val amount = "amount"
    const val priceId = "priceId"
    const val customerId = "customerId"
    const val productId = "productId"
    const val usd = "usd"
    const val searchUser = "searchUser"
    const val iRequesterId = "iRequesterId"
    const val userAccountType = "userAccountType"
    const val requestUserAccountType = "requestUserAccountType"
    const val eRequesterStatus = "eRequesterStatus"
    const val eUserAccountType = "eUserAccountType"
    const val vBio = "vBio"
    const val eTwoStepVerification = "eTwoStepVerification"
    const val eTwoStepVerificationType = "eTwoStepVerificationType"
    const val eReportType = "eReportType"
    const val iReportCategoryId = "iReportCategoryId"
    const val iReportSubcategoryId = "iReportSubcategoryId"
    const val iReportId = "iReportId"
    const val iReportUserId = "iReportUserId"
    const val tReportDescription = "tReportDescription"
    const val eKids_For = "eKids_For"
    const val eShare_To = "eShare_To"
    const val eFollow_Button = "eFollow_Button"
    const val tUsers = "tUsers"
    const val vEmbedLink = "vEmbedLink"
    const val vEmbedShortLink = "vEmbedShortLink"
    const val vDefultBackgroundColor = "vDefultBackgroundColor"
    const val vGif = "vGif"
    const val vComment = "vComment"
    const val iPostCommentId = "iPostCommentId"
    const val isReply = "isReply"
    const val iPostCommentReplyId = "iPostCommentReplyId"
    const val iCommentiUserid = "iCommentiUserid"
    const val iCommentReplyiUserid = "iCommentReplyiUserid"
    const val iFriendUserId = "iFriendUserId"
    const val vLinkImage = "vLinkImage"
    const val vLink = "vLink"
    const val vLinkDescription = "vLinkDescription"
    const val searchData = "searchData"
    const val vTeamMobileNumber="vTeamMobileNumber"
    const val eWebsiteType="eWebsiteType"
    const val vTeamAddress="vTeamAddress"

    enum class EventType {
        Event, Practice, Game, Training, Facility
    }

    enum class User {
        Sender, Receiver
    }

    enum class CalendarType {
        Personal, Master, Team
    }

    enum class SportType {
        Interactive, NonInteractive
    }

    enum class MediaType {
        Photo, Video
    }

    enum class eSportTypeEnum {
        Interactive, NonInteractive
    }
}